#!/usr/bin/env bash

git clone -b v0.10.1 https://github.com/neovim/neovim.git $HOME/yogi/neovim
brew install cmake gettext lua@5.3

cd $HOME/yogi/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
